[functions.register-owner]
verify_jwt = true

[functions.monthly-sales-report]
verify_jwt = false

[functions.manage-users]
enabled = true
verify_jwt = true
entrypoint = "./functions/manage-users/index.ts"
