BEGIN;

CREATE TABLE IF NOT EXISTS public.cys_registration_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  attempted_at timestamptz NOT NULL DEFAULT NOW()
);

ALTER TABLE public.cys_registration_attempts
ENABLE ROW LEVEL SECURITY;

REVOKE ALL
ON TABLE public.cys_registration_attempts
FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS
  cys_registration_attempts_user_time_idx
ON public.cys_registration_attempts (
  user_id,
  attempted_at DESC
);

CREATE OR REPLACE FUNCTION public.cys_consume_registration_attempt(
  p_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count integer;
  v_oldest timestamptz;
  v_retry integer;
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtext('cys-register-rate:' || p_user_id::text)
  );

  DELETE FROM public.cys_registration_attempts
  WHERE attempted_at < NOW() - INTERVAL '15 minutes';

  SELECT
    COUNT(*)::integer,
    MIN(attempted_at)
  INTO
    v_count,
    v_oldest
  FROM public.cys_registration_attempts
  WHERE user_id = p_user_id
    AND attempted_at >= NOW() - INTERVAL '15 minutes';

  IF v_count >= 10 THEN
    v_retry :=
      GREATEST(
        1,
        CEIL(
          EXTRACT(
            EPOCH FROM (
              v_oldest + INTERVAL '15 minutes' - NOW()
            )
          )
        )::integer
      );

    RETURN jsonb_build_object(
      'allowed', false,
      'retryAfterSeconds', v_retry
    );
  END IF;

  INSERT INTO public.cys_registration_attempts (
    user_id
  )
  VALUES (
    p_user_id
  );

  RETURN jsonb_build_object(
    'allowed', true,
    'remaining', 9 - v_count
  );
END;
$$;

REVOKE ALL
ON FUNCTION public.cys_consume_registration_attempt(uuid)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE
ON FUNCTION public.cys_consume_registration_attempt(uuid)
TO service_role;

COMMIT;
