BEGIN;

-- ============================================================
-- Registro de entregas de reportes
-- ============================================================

CREATE TABLE IF NOT EXISTS
  public.report_deliveries (
    id bigint
      GENERATED BY DEFAULT
      AS IDENTITY
      PRIMARY KEY,

    report_type text
      NOT NULL,

    period_key text
      NOT NULL,

    recipient_key text
      NOT NULL,

    status text
      NOT NULL
      DEFAULT 'sending',

    sales_count integer
      NOT NULL
      DEFAULT 0,

    total_amount bigint
      NOT NULL
      DEFAULT 0,

    provider_message_id text
      NULL,

    sent_at timestamptz
      NULL,

    last_error text
      NULL,

    created_at timestamptz
      NOT NULL
      DEFAULT NOW(),

    updated_at timestamptz
      NOT NULL
      DEFAULT NOW(),

    CONSTRAINT
      report_deliveries_type_valid
      CHECK (
        report_type IN (
          'monthly-sales'
        )
      ),

    CONSTRAINT
      report_deliveries_status_valid
      CHECK (
        status IN (
          'sending',
          'sent',
          'failed'
        )
      ),

    CONSTRAINT
      report_deliveries_sales_count_valid
      CHECK (
        sales_count >= 0
      ),

    CONSTRAINT
      report_deliveries_total_amount_valid
      CHECK (
        total_amount >= 0
      ),

    CONSTRAINT
      report_deliveries_unique_delivery
      UNIQUE (
        report_type,
        period_key,
        recipient_key
      )
  );

ALTER TABLE
  public.report_deliveries
ENABLE ROW LEVEL SECURITY;

-- No se crean policies para frontend.
-- Solo la Edge Function con clave secreta
-- puede leer/escribir esta tabla.


-- ============================================================
-- Snapshot del mes calendario anterior
-- Zona horaria comercial: Chile continental
-- ============================================================

CREATE OR REPLACE FUNCTION
  public.cys_monthly_report_snapshot(
    p_reference timestamptz
      DEFAULT NOW()
  )
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_timezone text :=
    'America/Santiago';

  v_reference_local timestamp;

  v_start_local timestamp;

  v_end_local timestamp;

  v_start_utc timestamptz;

  v_end_utc timestamptz;

  v_sales jsonb;
BEGIN
  v_reference_local :=
    timezone(
      v_timezone,
      p_reference
    );

  v_end_local :=
    date_trunc(
      'month',
      v_reference_local
    );

  v_start_local :=
    v_end_local -
    INTERVAL '1 month';

  v_start_utc :=
    v_start_local
      AT TIME ZONE
      v_timezone;

  v_end_utc :=
    v_end_local
      AT TIME ZONE
      v_timezone;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id',
          s.id::integer,

        'seller',
          COALESCE(
            s.seller_email,
            'Usuario eliminado'
          ),

        'soldAt',
          s.sold_at,

        'total',
          s.total_amount,

        'paymentMethod',
          s.payment_method,

        'installments',
          s.installments,

        'items',
          COALESCE(
            (
              SELECT jsonb_agg(
                jsonb_build_object(
                  'productId',
                    si.product_id::integer,

                  'name',
                    si.product_name,

                  'quantity',
                    si.quantity,

                  'unitPrice',
                    si.unit_price,

                  'subtotal',
                    si.subtotal
                )
                ORDER BY
                  si.id
              )
              FROM
                public.sale_items si
              WHERE
                si.sale_id =
                  s.id
            ),
            '[]'::jsonb
          )
      )
      ORDER BY
        s.sold_at ASC,
        s.id ASC
    ),
    '[]'::jsonb
  )
  INTO
    v_sales
  FROM
    public.sales s
  WHERE
    s.sold_at >=
      v_start_utc
    AND
    s.sold_at <
      v_end_utc;

  RETURN jsonb_build_object(
    'periodKey',
      to_char(
        v_start_local,
        'YYYY-MM'
      ),

    'periodStartLocal',
      to_char(
        v_start_local,
        'YYYY-MM-DD'
      ),

    'periodEndLocal',
      to_char(
        v_end_local,
        'YYYY-MM-DD'
      ),

    'timezone',
      v_timezone,

    'sales',
      v_sales
  );
END;
$$;


-- ============================================================
-- Permisos
-- ============================================================

REVOKE ALL
ON FUNCTION
  public.cys_monthly_report_snapshot(
    timestamptz
  )
FROM PUBLIC;

REVOKE ALL
ON FUNCTION
  public.cys_monthly_report_snapshot(
    timestamptz
  )
FROM anon;

REVOKE ALL
ON FUNCTION
  public.cys_monthly_report_snapshot(
    timestamptz
  )
FROM authenticated;

GRANT EXECUTE
ON FUNCTION
  public.cys_monthly_report_snapshot(
    timestamptz
  )
TO service_role;

COMMIT;
