BEGIN;

-- ============================================================
-- Proveedores + ubicación física + stock inicial
-- ============================================================

CREATE TABLE IF NOT EXISTS public.suppliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT suppliers_name_not_blank
    CHECK (BTRIM(name) <> ''),
  CONSTRAINT suppliers_name_length
    CHECK (CHAR_LENGTH(BTRIM(name)) <= 100)
);

ALTER TABLE public.suppliers
ENABLE ROW LEVEL SECURITY;

-- No se crean policies directas:
-- proveedores se administra exclusivamente mediante RPC autorizadas.

CREATE OR REPLACE FUNCTION public.cys_normalize_supplier_name(
  p_name text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = ''
AS $$
  SELECT LOWER(
    TRANSLATE(
      BTRIM(COALESCE(p_name, '')),
      'áéíóúÁÉÍÓÚ',
      'aeiouAEIOU'
    )
  );
$$;

REVOKE ALL
ON FUNCTION public.cys_normalize_supplier_name(text)
FROM PUBLIC;

CREATE UNIQUE INDEX IF NOT EXISTS
  suppliers_normalized_name_unique
ON public.suppliers (
  public.cys_normalize_supplier_name(name)
);

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS supplier_id bigint NULL,
  ADD COLUMN IF NOT EXISTS location text NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'products_supplier_id_fkey'
      AND conrelid = 'public.products'::regclass
  ) THEN
    ALTER TABLE public.products
      ADD CONSTRAINT products_supplier_id_fkey
      FOREIGN KEY (supplier_id)
      REFERENCES public.suppliers(id)
      ON DELETE RESTRICT;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'products_location_length'
      AND conrelid = 'public.products'::regclass
  ) THEN
    ALTER TABLE public.products
      ADD CONSTRAINT products_location_length
      CHECK (
        location IS NULL
        OR CHAR_LENGTH(BTRIM(location)) <= 120
      );
  END IF;
END;
$$;


-- ============================================================
-- Productos: lectura
-- ============================================================

CREATE OR REPLACE FUNCTION public.cys_list_products(
  p_page integer DEFAULT 1,
  p_limit integer DEFAULT 25,
  p_search text DEFAULT NULL,
  p_category text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_page integer := GREATEST(COALESCE(p_page, 1), 1);
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 25), 1), 100);
  v_offset integer;
  v_total integer;
  v_total_pages integer;
  v_data jsonb;
  v_search text := NULLIF(BTRIM(COALESCE(p_search, '')), '');
  v_category text := NULLIF(BTRIM(COALESCE(p_category, '')), '');
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  v_offset := (v_page - 1) * v_limit;

  SELECT COUNT(*)::integer
  INTO v_total
  FROM public.products p
  WHERE (
      v_search IS NULL
      OR p.name ILIKE '%' || v_search || '%'
      OR p.brand ILIKE '%' || v_search || '%'
      OR p.sku ILIKE '%' || v_search || '%'
    )
    AND (
      v_category IS NULL
      OR p.category = v_category
    );

  v_total_pages :=
    GREATEST(1, CEIL(v_total::numeric / v_limit)::integer);

  SELECT COALESCE(
    jsonb_agg(row_data ORDER BY created_at DESC, id DESC),
    '[]'::jsonb
  )
  INTO v_data
  FROM (
    SELECT
      p.id,
      p.created_at,
      jsonb_build_object(
        'id', p.id::integer,
        'name', p.name,
        'brand', p.brand,
        'sku', p.sku,
        'category', p.category,
        'supplierId', p.supplier_id,
        'supplierName', (
          SELECT s.name
          FROM public.suppliers s
          WHERE s.id = p.supplier_id
        ),
        'location', p.location,
        'netPrice', p.net_price,
        'priceWithTax', p.price_with_tax,
        'price', p.price,
        'stock', p.stock,
        'shortDescription', p.short_description,
        'description', p.description,
        'createdAt', p.created_at,
        'updatedAt', p.updated_at,
        'images',
          COALESCE(
            (
              SELECT jsonb_agg(
                jsonb_build_object(
                  'id', pi.id::integer,
                  'storagePath', pi.storage_path,
                  'externalUrl', pi.external_url,
                  'position', pi.position
                )
                ORDER BY pi.position
              )
              FROM public.product_images pi
              WHERE pi.product_id = p.id
            ),
            '[]'::jsonb
          )
      ) AS row_data
    FROM public.products p
    WHERE (
        v_search IS NULL
        OR p.name ILIKE '%' || v_search || '%'
        OR p.brand ILIKE '%' || v_search || '%'
        OR p.sku ILIKE '%' || v_search || '%'
      )
      AND (
        v_category IS NULL
        OR p.category = v_category
      )
    ORDER BY p.created_at DESC, p.id DESC
    LIMIT v_limit
    OFFSET v_offset
  ) q;

  RETURN jsonb_build_object(
    'data', v_data,
    'pagination',
      jsonb_build_object(
        'page', v_page,
        'limit', v_limit,
        'total', v_total,
        'totalPages', v_total_pages,
        'hasPreviousPage', v_page > 1,
        'hasNextPage', v_page < v_total_pages
      )
  );
END;
$$;


CREATE OR REPLACE FUNCTION public.cys_get_product(
  p_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'id', p.id::integer,
    'name', p.name,
    'brand', p.brand,
    'sku', p.sku,
    'category', p.category,
    'supplierId', p.supplier_id,
    'supplierName', (
      SELECT s.name
      FROM public.suppliers s
      WHERE s.id = p.supplier_id
    ),
    'location', p.location,
    'netPrice', p.net_price,
    'priceWithTax', p.price_with_tax,
    'price', p.price,
    'stock', p.stock,
    'shortDescription', p.short_description,
    'description', p.description,
    'createdAt', p.created_at,
    'updatedAt', p.updated_at,
    'images',
      COALESCE(
        (
          SELECT jsonb_agg(
            jsonb_build_object(
              'id', pi.id::integer,
              'storagePath', pi.storage_path,
              'externalUrl', pi.external_url,
              'position', pi.position
            )
            ORDER BY pi.position
          )
          FROM public.product_images pi
          WHERE pi.product_id = p.id
        ),
        '[]'::jsonb
      )
  )
  INTO v_result
  FROM public.products p
  WHERE p.id = p_id;

  RETURN v_result;
END;
$$;


-- ============================================================
-- Productos: escritura
-- Se eliminan las firmas antiguas para evitar RPC sobrecargadas.
-- ============================================================

DROP FUNCTION IF EXISTS public.cys_create_product(
  text,
  text,
  text,
  text,
  integer,
  integer,
  text,
  text
);

CREATE FUNCTION public.cys_create_product(
  p_name text,
  p_brand text,
  p_sku text,
  p_category text,
  p_supplier_id bigint,
  p_location text,
  p_net_price integer,
  p_price integer,
  p_stock integer,
  p_short_description text,
  p_description text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_id bigint;
  v_location text :=
    NULLIF(BTRIM(COALESCE(p_location, '')), '');
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  IF p_stock IS NULL OR p_stock < 0 THEN
    RAISE EXCEPTION 'El stock no puede ser negativo.';
  END IF;

  IF CHAR_LENGTH(COALESCE(v_location, '')) > 120 THEN
    RAISE EXCEPTION 'La ubicación no puede superar los 120 caracteres.';
  END IF;

  IF
    p_supplier_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM public.suppliers s
      WHERE s.id = p_supplier_id
    )
  THEN
    RAISE EXCEPTION 'El proveedor no existe.'
      USING ERRCODE = '23503';
  END IF;

  INSERT INTO public.products (
    name,
    brand,
    sku,
    category,
    supplier_id,
    location,
    net_price,
    price,
    stock,
    short_description,
    description
  )
  VALUES (
    BTRIM(p_name),
    BTRIM(p_brand),
    BTRIM(p_sku),
    BTRIM(p_category),
    p_supplier_id,
    v_location,
    p_net_price,
    p_price,
    p_stock,
    BTRIM(p_short_description),
    BTRIM(p_description)
  )
  RETURNING id
  INTO v_id;

  RETURN public.cys_get_product(v_id);
END;
$$;


DROP FUNCTION IF EXISTS public.cys_update_product(
  bigint,
  text,
  text,
  text,
  text,
  integer,
  integer,
  integer,
  text,
  text
);

CREATE FUNCTION public.cys_update_product(
  p_id bigint,
  p_name text,
  p_brand text,
  p_sku text,
  p_category text,
  p_supplier_id bigint,
  p_location text,
  p_net_price integer,
  p_price integer,
  p_stock integer,
  p_short_description text,
  p_description text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_location text :=
    NULLIF(BTRIM(COALESCE(p_location, '')), '');
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  IF p_stock IS NULL OR p_stock < 0 THEN
    RAISE EXCEPTION 'El stock no puede ser negativo.';
  END IF;

  IF CHAR_LENGTH(COALESCE(v_location, '')) > 120 THEN
    RAISE EXCEPTION 'La ubicación no puede superar los 120 caracteres.';
  END IF;

  IF
    p_supplier_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM public.suppliers s
      WHERE s.id = p_supplier_id
    )
  THEN
    RAISE EXCEPTION 'El proveedor no existe.'
      USING ERRCODE = '23503';
  END IF;

  UPDATE public.products
  SET
    name = BTRIM(p_name),
    brand = BTRIM(p_brand),
    sku = BTRIM(p_sku),
    category = BTRIM(p_category),
    supplier_id = p_supplier_id,
    location = v_location,
    net_price = p_net_price,
    price = p_price,
    stock = p_stock,
    short_description = BTRIM(p_short_description),
    description = BTRIM(p_description),
    updated_at = NOW()
  WHERE id = p_id;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN public.cys_get_product(p_id);
END;
$$;


-- ============================================================
-- Proveedores
-- ============================================================

CREATE OR REPLACE FUNCTION public.cys_list_suppliers()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', s.id::integer,
        'name', s.name,
        'createdAt', s.created_at,
        'productCount', (
          SELECT COUNT(*)::integer
          FROM public.products p
          WHERE p.supplier_id = s.id
        )
      )
      ORDER BY LOWER(s.name)
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM public.suppliers s;

  RETURN v_result;
END;
$$;


CREATE OR REPLACE FUNCTION public.cys_create_supplier(
  p_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_supplier public.suppliers%ROWTYPE;
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  IF
    NULLIF(BTRIM(COALESCE(p_name, '')), '') IS NULL
  THEN
    RAISE EXCEPTION 'El nombre del proveedor es obligatorio.';
  END IF;

  INSERT INTO public.suppliers (name)
  VALUES (BTRIM(p_name))
  RETURNING *
  INTO v_supplier;

  RETURN jsonb_build_object(
    'id', v_supplier.id::integer,
    'name', v_supplier.name,
    'createdAt', v_supplier.created_at,
    'productCount', 0
  );
END;
$$;


CREATE OR REPLACE FUNCTION public.cys_delete_supplier(
  p_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_supplier public.suppliers%ROWTYPE;
  v_product_count integer;
BEGIN
  IF NOT public.cys_is_authorized_user() THEN
    RAISE EXCEPTION 'No autorizado.' USING ERRCODE = '42501';
  END IF;

  SELECT *
  INTO v_supplier
  FROM public.suppliers
  WHERE id = p_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'not-found');
  END IF;

  SELECT COUNT(*)::integer
  INTO v_product_count
  FROM public.products
  WHERE supplier_id = v_supplier.id;

  IF v_product_count > 0 THEN
    RETURN jsonb_build_object(
      'status', 'in-use',
      'productCount', v_product_count
    );
  END IF;

  DELETE FROM public.suppliers
  WHERE id = p_id;

  RETURN jsonb_build_object(
    'status', 'deleted',
    'supplier',
      jsonb_build_object(
        'id', v_supplier.id::integer,
        'name', v_supplier.name
      )
  );
END;
$$;


-- ============================================================
-- Permisos RPC
-- ============================================================

REVOKE ALL ON FUNCTION public.cys_create_product(
  text,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  integer,
  integer,
  text,
  text
) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.cys_update_product(
  bigint,
  text,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  integer,
  integer,
  text,
  text
) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.cys_list_suppliers()
FROM PUBLIC;

REVOKE ALL ON FUNCTION public.cys_create_supplier(text)
FROM PUBLIC;

REVOKE ALL ON FUNCTION public.cys_delete_supplier(bigint)
FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.cys_create_product(
  text,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  integer,
  integer,
  text,
  text
) TO authenticated;

GRANT EXECUTE ON FUNCTION public.cys_update_product(
  bigint,
  text,
  text,
  text,
  text,
  bigint,
  text,
  integer,
  integer,
  integer,
  text,
  text
) TO authenticated;

GRANT EXECUTE ON FUNCTION public.cys_list_suppliers()
TO authenticated;

GRANT EXECUTE ON FUNCTION public.cys_create_supplier(text)
TO authenticated;

GRANT EXECUTE ON FUNCTION public.cys_delete_supplier(bigint)
TO authenticated;

COMMIT;
